### ISSUE TITLE
Help/Examples: Example image viewer: Toolbar's Up button takes us back to examples for first question.

### ISSUE THREAD

**Issue by ghost** [murraycu/android-galaxyzoo#14]
When in the help of the bar/no bar section, clicking on a picture then going back open the first help (smooth, features or disk, star or artefact) instead of the bar/no bar

On version 1.32

**Comment by murraycu** [comment]
Thanks for reporting this. I can reproduce it. It only happens when you use the back/up arrow on the app bar at the top. It doesn't happen when you use the regular back button. This is like this bug:
https://github.com/murraycu/android-galaxyzoo/issues/6

It should be easy enough to fix but I won't have a chance until some time next week.
